name: nestjs-lab

services:
  mysql:
    image: mysql:8.4.4
    restart: always
    env_file:
      - ./../.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: my_app_database
    ports:
      - '3306:3306'
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    healthcheck:
      test: ['CMD-SHELL', 'mysladmin ping -h 127.0.0.1']
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s
